// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBlog.Models;

namespace TravelBlog.Migrations
{
    [DbContext(typeof(TravelBlogContext))]
    [Migration("20200402222440_Swag")]
    partial class Swag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelBlog.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<int>("Year");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 6,
                            Location = "Oregon",
                            Year = 1859
                        },
                        new
                        {
                            DestinationId = 7,
                            Location = "Washington",
                            Year = 1889
                        },
                        new
                        {
                            DestinationId = 8,
                            Location = "Idaho",
                            Year = 1890
                        });
                });

            modelBuilder.Entity("TravelBlog.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("DestinationId");

                    b.Property<int>("Rating");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "It was wonderful",
                            DestinationId = 6,
                            Rating = 5,
                            Title = "Oregon"
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "It was wonderful",
                            DestinationId = 7,
                            Rating = 4,
                            Title = "Washington"
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "It was wonderful",
                            DestinationId = 8,
                            Rating = 3,
                            Title = "Idaho"
                        });
                });

            modelBuilder.Entity("TravelBlog.Models.Review", b =>
                {
                    b.HasOne("TravelBlog.Models.Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
